### ISSUE TITLE
ruby deps in debian control file

### ISSUE THREAD

**Issue by annaborn** [rock-core/tools-apaka#8]
Hello @2maz Thomas,

as I wrote you in email, there was an issue with ruby dependencies. That ruby libs that already presented as debian packages, still was included in Depends section. E.g. ruby-generator (s. output below) This problem comes also in other packages. 
I could find out, that the substvar ${ruby:Depends}, which get added to debian/control file, causes this error. 
Since all required dependencies get injected by apaka, I decided to remove substvar ruby:Depends from the control file. 
https://github.com/annaborn/tools-apaka/commit/e26a5a2f510d4492011397f9789f3a9d86bea1a6

My question is, is it safe way to do? Does apaka really add all required dependencies? And should we delete also other substvars, that are added by default: ${misc:Depends}, ${shlibs:Depends} ?

Here you can find more about substvar: https://www.debian.org/doc/manuals/debmake-doc/ch05.en.html

```
Package: rock-master-22.04-ruby-stream
Version: 0.5.3-1~focal
Architecture: amd64
Maintainer: Rock Packaging Daemon (based on apaka) [<rock-dev@dfki.de>](mailto:rock-dev@dfki.de)
Installed-Size: 678
Depends: ruby-generator, rock-master-22.04-ruby-generator, ruby
Homepage: https://github.com/monora/stream
Priority: optional
Section: science
Filename: pool/main/r/rock-master-22.04-ruby-stream/rock-master-22.04-ruby-stream_0.5.3-1~focal_amd64.deb
Size: 111536
SHA256: 53d42c5963d62139dcedd8a33fa7f94bccabeda32bc1c75d3fd4f4370d67e883
SHA1: e0388d177fbaa7db0fc01f44b9b7893653a85168
MD5sum: 5c0845f78902e3c8b3d168dbefa4425c
Description: stream - Extended External Iterators
 Module Stream defines an interface for external iterators.
Ruby-Versions: all
```

**Comment by 2maz** [comment]
Previously generated ruby packages, e.g., see master-20.10 do not contain `${ruby:Depends}`, but it looks like an update in gem2deb. So `${ruby:Depends}` actually needs to be removed, since otherwise system default versions of the dependencies will always be present. 
The other default set of substvar I would keep, unless you see similar conflicts.

**Comment by annaborn** [comment]
Resolved in https://github.com/rock-core/tools-apaka/commit/3b769fa4ea8b03062a8ee93919bb1f5e98f3d4c3
